export {
    FaBars,
    FaArrowLeft,
    FaPlus,
    FaMoon,
    FaMagnifyingGlass,
    FaBell,
    FaHouse,
    FaList,
    FaCheck,
    FaCircleInfo,
    FaGear,
    FaRightToBracket,
    FaRightFromBracket,
    FaUser,
    FaUserPlus,
    FaHeart,
    FaFilePen,
    FaUserGroup,
    FaClipboardList,
    FaCaretDown,
    FaTrash,
    FaLock,
    FaLinkedin,
    FaEnvelope,
} from 'react-icons/fa6'

export type { IconType } from 'react-icons'
